//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod groups;
pub mod notifications;
pub mod permission_links;
pub mod permissions;
pub mod settings;
pub mod user_group_links;
pub mod users;
