// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package utils

import (
	"sort"
	"sync"
)

type IntElement struct {
	Key   int
	Value interface{}
}

type IntSorterFunc func(a *IntElement, b *IntElement) bool

type IntMap struct {
	Data sync.Map
}

func (m *IntMap) Clear() {
	m.Data = sync.Map{}
}

func (m *IntMap) Len() int {
	return len(m.Keys())
}

func (m *IntMap) Get(k int) (interface{}, bool) {
	ret, ok := m.Data.Load(k)
	if ret == nil {
		return nil, false
	}
	return ret.(interface{}), ok
}

func (m *IntMap) MustGet(k int) interface{} {
	ret, ok := m.Get(k)
	if !ok {
		panic("key not found")
	}
	return ret
}

func (m *IntMap) Set(k int, v interface{}) {
	m.Data.Store(k, v)
}

func (m *IntMap) SetIfAbsent(k int, v interface{}) (interface{}, bool) {
	ret, ok := m.Data.LoadOrStore(k, v)
	if ret == nil {
		panic("value is nil")
	}
	return ret.(interface{}), ok
}

func (m *IntMap) Delete(k int) {
	m.Data.Delete(k)
}

func (m *IntMap) Has(k int) bool {
	_, ok := m.Data.Load(k)
	return ok
}

func (m *IntMap) Range(f func(k int, v interface{}) bool) {
	m.Data.Range(func(key, value interface{}) bool {
		return f(key.(int), value.(interface{}))
	})
}

func (m *IntMap) Keys() []int {
	var ret []int
	m.Range(func(key int, value interface{}) bool {
		ret = append(ret, key)
		return true
	})
	return ret
}

func (m *IntMap) Values() []interface{} {
	var ret []interface{}
	m.Range(func(key int, value interface{}) bool {
		ret = append(ret, value)
		return true
	})
	return ret
}

func (m *IntMap) Elements() []*IntElement {
	var ret []*IntElement
	m.Range(func(key int, value interface{}) bool {
		ret = append(ret, &IntElement{
			Key:   key,
			Value: value,
		})
		return true
	})
	return ret
}

func (m *IntMap) Map() map[int]interface{} {
	ret := make(map[int]interface{})
	m.Range(func(key int, value interface{}) bool {
		ret[key] = value
		return true
	})
	return ret
}

func (m *IntMap) SortElement(f IntSorterFunc) []*IntElement {
	ret := m.Elements()
	sort.SliceStable(ret, func(i, j int) bool {
		return f(ret[i], ret[j])
	})
	return ret
}

func (m *IntMap) SortKey(f IntSorterFunc) []int {
	res := m.SortElement(f)
	var ret []int
	for _, v := range res {
		ret = append(ret, v.Key)
	}
	return ret
}

func (m *IntMap) SortValue(f IntSorterFunc) []interface{} {
	res := m.SortElement(f)
	var ret []interface{}
	for _, v := range res {
		ret = append(ret, v.Value)
	}
	return ret
}
