// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: common.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage_MsgType int32

const (
	AgentMessage_UNKNOWN AgentMessage_MsgType = 0
	AgentMessage_LOGIN   AgentMessage_MsgType = 1 // agent login
	AgentMessage_RETURN  AgentMessage_MsgType = 2 // return value message
	AgentMessage_INFO    AgentMessage_MsgType = 3 // agent info
	AgentMessage_STATUS  AgentMessage_MsgType = 4 // status req/rsp
	AgentMessage_COMMAND AgentMessage_MsgType = 5 // command operation
	AgentMessage_FILE    AgentMessage_MsgType = 6 // send file
	AgentMessage_SHELL   AgentMessage_MsgType = 7 // shell operation
	AgentMessage_RESTART AgentMessage_MsgType = 8 // restart
)

// Enum value maps for AgentMessage_MsgType.
var (
	AgentMessage_MsgType_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOGIN",
		2: "RETURN",
		3: "INFO",
		4: "STATUS",
		5: "COMMAND",
		6: "FILE",
		7: "SHELL",
		8: "RESTART",
	}
	AgentMessage_MsgType_value = map[string]int32{
		"UNKNOWN": 0,
		"LOGIN":   1,
		"RETURN":  2,
		"INFO":    3,
		"STATUS":  4,
		"COMMAND": 5,
		"FILE":    6,
		"SHELL":   7,
		"RESTART": 8,
	}
)

func (x AgentMessage_MsgType) Enum() *AgentMessage_MsgType {
	p := new(AgentMessage_MsgType)
	*p = x
	return p
}

func (x AgentMessage_MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMessage_MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (AgentMessage_MsgType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x AgentMessage_MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMessage_MsgType.Descriptor instead.
func (AgentMessage_MsgType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 0}
}

type ReturnMessage_ReturnCode int32

const (
	ReturnMessage_OK         ReturnMessage_ReturnCode = 0
	ReturnMessage_ERROR      ReturnMessage_ReturnCode = -1
	ReturnMessage_INVALID    ReturnMessage_ReturnCode = 1
	ReturnMessage_ONLINE     ReturnMessage_ReturnCode = 2
	ReturnMessage_NEED_LOGIN ReturnMessage_ReturnCode = 3
)

// Enum value maps for ReturnMessage_ReturnCode.
var (
	ReturnMessage_ReturnCode_name = map[int32]string{
		0:  "OK",
		-1: "ERROR",
		1:  "INVALID",
		2:  "ONLINE",
		3:  "NEED_LOGIN",
	}
	ReturnMessage_ReturnCode_value = map[string]int32{
		"OK":         0,
		"ERROR":      -1,
		"INVALID":    1,
		"ONLINE":     2,
		"NEED_LOGIN": 3,
	}
)

func (x ReturnMessage_ReturnCode) Enum() *ReturnMessage_ReturnCode {
	p := new(ReturnMessage_ReturnCode)
	*p = x
	return p
}

func (x ReturnMessage_ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnMessage_ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ReturnMessage_ReturnCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ReturnMessage_ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnMessage_ReturnCode.Descriptor instead.
func (ReturnMessage_ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1, 0}
}

type CommandMessage_CommandType int32

const (
	CommandMessage_UNKNOWN CommandMessage_CommandType = 0
	CommandMessage_RUN     CommandMessage_CommandType = 1
	CommandMessage_RESULT  CommandMessage_CommandType = 2
	CommandMessage_KILL    CommandMessage_CommandType = 3
)

// Enum value maps for CommandMessage_CommandType.
var (
	CommandMessage_CommandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUN",
		2: "RESULT",
		3: "KILL",
	}
	CommandMessage_CommandType_value = map[string]int32{
		"UNKNOWN": 0,
		"RUN":     1,
		"RESULT":  2,
		"KILL":    3,
	}
)

func (x CommandMessage_CommandType) Enum() *CommandMessage_CommandType {
	p := new(CommandMessage_CommandType)
	*p = x
	return p
}

func (x CommandMessage_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandMessage_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (CommandMessage_CommandType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x CommandMessage_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandMessage_CommandType.Descriptor instead.
func (CommandMessage_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2, 0}
}

type AgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type AgentMessage_MsgType `protobuf:"varint,2,opt,name=type,proto3,enum=msg.AgentMessage_MsgType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*AgentMessage_Login
	//	*AgentMessage_Return
	//	*AgentMessage_StatusReq
	//	*AgentMessage_StatusRsp
	//	*AgentMessage_Info
	//	*AgentMessage_Command
	//	*AgentMessage_File
	//	*AgentMessage_Shell
	Data isAgentMessage_Data `protobuf_oneof:"data"`
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMessage) GetType() AgentMessage_MsgType {
	if x != nil {
		return x.Type
	}
	return AgentMessage_UNKNOWN
}

func (m *AgentMessage) GetData() isAgentMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *AgentMessage) GetLogin() *LoginMessage {
	if x, ok := x.GetData().(*AgentMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *AgentMessage) GetReturn() *ReturnMessage {
	if x, ok := x.GetData().(*AgentMessage_Return); ok {
		return x.Return
	}
	return nil
}

func (x *AgentMessage) GetStatusReq() *StatusReqMessage {
	if x, ok := x.GetData().(*AgentMessage_StatusReq); ok {
		return x.StatusReq
	}
	return nil
}

func (x *AgentMessage) GetStatusRsp() *StatusRspMessage {
	if x, ok := x.GetData().(*AgentMessage_StatusRsp); ok {
		return x.StatusRsp
	}
	return nil
}

func (x *AgentMessage) GetInfo() *InfoMessage {
	if x, ok := x.GetData().(*AgentMessage_Info); ok {
		return x.Info
	}
	return nil
}

func (x *AgentMessage) GetCommand() *CommandMessage {
	if x, ok := x.GetData().(*AgentMessage_Command); ok {
		return x.Command
	}
	return nil
}

func (x *AgentMessage) GetFile() *FileMessage {
	if x, ok := x.GetData().(*AgentMessage_File); ok {
		return x.File
	}
	return nil
}

func (x *AgentMessage) GetShell() *ShellMessage {
	if x, ok := x.GetData().(*AgentMessage_Shell); ok {
		return x.Shell
	}
	return nil
}

type isAgentMessage_Data interface {
	isAgentMessage_Data()
}

type AgentMessage_Login struct {
	Login *LoginMessage `protobuf:"bytes,3,opt,name=login,proto3,oneof"`
}

type AgentMessage_Return struct {
	Return *ReturnMessage `protobuf:"bytes,4,opt,name=return,proto3,oneof"`
}

type AgentMessage_StatusReq struct {
	StatusReq *StatusReqMessage `protobuf:"bytes,5,opt,name=statusReq,proto3,oneof"`
}

type AgentMessage_StatusRsp struct {
	StatusRsp *StatusRspMessage `protobuf:"bytes,6,opt,name=statusRsp,proto3,oneof"`
}

type AgentMessage_Info struct {
	Info *InfoMessage `protobuf:"bytes,7,opt,name=info,proto3,oneof"`
}

type AgentMessage_Command struct {
	Command *CommandMessage `protobuf:"bytes,8,opt,name=command,proto3,oneof"`
}

type AgentMessage_File struct {
	File *FileMessage `protobuf:"bytes,9,opt,name=file,proto3,oneof"`
}

type AgentMessage_Shell struct {
	Shell *ShellMessage `protobuf:"bytes,10,opt,name=shell,proto3,oneof"`
}

func (*AgentMessage_Login) isAgentMessage_Data() {}

func (*AgentMessage_Return) isAgentMessage_Data() {}

func (*AgentMessage_StatusReq) isAgentMessage_Data() {}

func (*AgentMessage_StatusRsp) isAgentMessage_Data() {}

func (*AgentMessage_Info) isAgentMessage_Data() {}

func (*AgentMessage_Command) isAgentMessage_Data() {}

func (*AgentMessage_File) isAgentMessage_Data() {}

func (*AgentMessage_Shell) isAgentMessage_Data() {}

type ReturnMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ReturnMessage_ReturnCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ReturnMessage_ReturnCode" json:"code,omitempty"` // return code
	Data string                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                    // return data
}

func (x *ReturnMessage) Reset() {
	*x = ReturnMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnMessage) ProtoMessage() {}

func (x *ReturnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnMessage.ProtoReflect.Descriptor instead.
func (*ReturnMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnMessage) GetCode() ReturnMessage_ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnMessage_OK
}

func (x *ReturnMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CommandMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type CommandMessage_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=msg.CommandMessage_CommandType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*CommandMessage_Run
	//	*CommandMessage_Kill
	//	*CommandMessage_Res
	Data isCommandMessage_Data `protobuf_oneof:"data"`
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *CommandMessage) GetType() CommandMessage_CommandType {
	if x != nil {
		return x.Type
	}
	return CommandMessage_UNKNOWN
}

func (m *CommandMessage) GetData() isCommandMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *CommandMessage) GetRun() *CMDRunMessage {
	if x, ok := x.GetData().(*CommandMessage_Run); ok {
		return x.Run
	}
	return nil
}

func (x *CommandMessage) GetKill() *CMDKillMessage {
	if x, ok := x.GetData().(*CommandMessage_Kill); ok {
		return x.Kill
	}
	return nil
}

func (x *CommandMessage) GetRes() *CMDResMessage {
	if x, ok := x.GetData().(*CommandMessage_Res); ok {
		return x.Res
	}
	return nil
}

type isCommandMessage_Data interface {
	isCommandMessage_Data()
}

type CommandMessage_Run struct {
	Run *CMDRunMessage `protobuf:"bytes,2,opt,name=run,proto3,oneof"`
}

type CommandMessage_Kill struct {
	Kill *CMDKillMessage `protobuf:"bytes,3,opt,name=kill,proto3,oneof"`
}

type CommandMessage_Res struct {
	Res *CMDResMessage `protobuf:"bytes,4,opt,name=res,proto3,oneof"`
}

func (*CommandMessage_Run) isCommandMessage_Data() {}

func (*CommandMessage_Kill) isCommandMessage_Data() {}

func (*CommandMessage_Res) isCommandMessage_Data() {}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x6d, 0x73, 0x67, 0x1a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x04, 0x0a, 0x0c,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x12, 0x35, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x35, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x73, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x73, 0x70, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x22, 0x72,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x54, 0x55, 0x52, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x10, 0x05,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48,
	0x45, 0x4c, 0x4c, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x10, 0x08, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa9, 0x01, 0x0a, 0x0d, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x45, 0x44, 0x5f, 0x4c,
	0x4f, 0x47, 0x49, 0x4e, 0x10, 0x03, 0x22, 0x83, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26,
	0x0a, 0x03, 0x72, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x4d, 0x44, 0x52, 0x75, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x4d, 0x44, 0x4b, 0x69,
	0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x6c,
	0x6c, 0x12, 0x26, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x4d, 0x44, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x55, 0x4e, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x49,
	0x4c, 0x4c, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []interface{}{
	(AgentMessage_MsgType)(0),       // 0: msg.AgentMessage.MsgType
	(ReturnMessage_ReturnCode)(0),   // 1: msg.ReturnMessage.ReturnCode
	(CommandMessage_CommandType)(0), // 2: msg.CommandMessage.CommandType
	(*AgentMessage)(nil),            // 3: msg.AgentMessage
	(*ReturnMessage)(nil),           // 4: msg.ReturnMessage
	(*CommandMessage)(nil),          // 5: msg.CommandMessage
	(*LoginMessage)(nil),            // 6: msg.LoginMessage
	(*StatusReqMessage)(nil),        // 7: msg.StatusReqMessage
	(*StatusRspMessage)(nil),        // 8: msg.StatusRspMessage
	(*InfoMessage)(nil),             // 9: msg.InfoMessage
	(*FileMessage)(nil),             // 10: msg.FileMessage
	(*ShellMessage)(nil),            // 11: msg.ShellMessage
	(*CMDRunMessage)(nil),           // 12: msg.CMDRunMessage
	(*CMDKillMessage)(nil),          // 13: msg.CMDKillMessage
	(*CMDResMessage)(nil),           // 14: msg.CMDResMessage
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: msg.AgentMessage.type:type_name -> msg.AgentMessage.MsgType
	6,  // 1: msg.AgentMessage.login:type_name -> msg.LoginMessage
	4,  // 2: msg.AgentMessage.return:type_name -> msg.ReturnMessage
	7,  // 3: msg.AgentMessage.statusReq:type_name -> msg.StatusReqMessage
	8,  // 4: msg.AgentMessage.statusRsp:type_name -> msg.StatusRspMessage
	9,  // 5: msg.AgentMessage.info:type_name -> msg.InfoMessage
	5,  // 6: msg.AgentMessage.command:type_name -> msg.CommandMessage
	10, // 7: msg.AgentMessage.file:type_name -> msg.FileMessage
	11, // 8: msg.AgentMessage.shell:type_name -> msg.ShellMessage
	1,  // 9: msg.ReturnMessage.code:type_name -> msg.ReturnMessage.ReturnCode
	2,  // 10: msg.CommandMessage.type:type_name -> msg.CommandMessage.CommandType
	12, // 11: msg.CommandMessage.run:type_name -> msg.CMDRunMessage
	13, // 12: msg.CommandMessage.kill:type_name -> msg.CMDKillMessage
	14, // 13: msg.CommandMessage.res:type_name -> msg.CMDResMessage
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_agent_proto_init()
	file_server_proto_init()
	file_shell_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AgentMessage_Login)(nil),
		(*AgentMessage_Return)(nil),
		(*AgentMessage_StatusReq)(nil),
		(*AgentMessage_StatusRsp)(nil),
		(*AgentMessage_Info)(nil),
		(*AgentMessage_Command)(nil),
		(*AgentMessage_File)(nil),
		(*AgentMessage_Shell)(nil),
	}
	file_common_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CommandMessage_Run)(nil),
		(*CommandMessage_Kill)(nil),
		(*CommandMessage_Res)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
