// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: shell.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellMessage_MsgType int32

const (
	ShellMessage_UNKNOWN    ShellMessage_MsgType = 0
	ShellMessage_ERROR      ShellMessage_MsgType = 1 // error message
	ShellMessage_INPUT      ShellMessage_MsgType = 2 // input message
	ShellMessage_OUTPUT     ShellMessage_MsgType = 3 // output message
	ShellMessage_SIZE       ShellMessage_MsgType = 4 // resize message
	ShellMessage_CONNECT    ShellMessage_MsgType = 5 // shell connect message
	ShellMessage_DISCONNECT ShellMessage_MsgType = 6 // shell disconnect message
)

// Enum value maps for ShellMessage_MsgType.
var (
	ShellMessage_MsgType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ERROR",
		2: "INPUT",
		3: "OUTPUT",
		4: "SIZE",
		5: "CONNECT",
		6: "DISCONNECT",
	}
	ShellMessage_MsgType_value = map[string]int32{
		"UNKNOWN":    0,
		"ERROR":      1,
		"INPUT":      2,
		"OUTPUT":     3,
		"SIZE":       4,
		"CONNECT":    5,
		"DISCONNECT": 6,
	}
)

func (x ShellMessage_MsgType) Enum() *ShellMessage_MsgType {
	p := new(ShellMessage_MsgType)
	*p = x
	return p
}

func (x ShellMessage_MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShellMessage_MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_shell_proto_enumTypes[0].Descriptor()
}

func (ShellMessage_MsgType) Type() protoreflect.EnumType {
	return &file_shell_proto_enumTypes[0]
}

func (x ShellMessage_MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShellMessage_MsgType.Descriptor instead.
func (ShellMessage_MsgType) EnumDescriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{0, 0}
}

type ShellMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  string               `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"` // shell conn id
	Type ShellMessage_MsgType `protobuf:"varint,2,opt,name=type,proto3,enum=msg.ShellMessage_MsgType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*ShellMessage_Size
	//	*ShellMessage_Connect
	//	*ShellMessage_Error
	//	*ShellMessage_Putdata
	Data isShellMessage_Data `protobuf_oneof:"data"`
}

func (x *ShellMessage) Reset() {
	*x = ShellMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellMessage) ProtoMessage() {}

func (x *ShellMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellMessage.ProtoReflect.Descriptor instead.
func (*ShellMessage) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{0}
}

func (x *ShellMessage) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *ShellMessage) GetType() ShellMessage_MsgType {
	if x != nil {
		return x.Type
	}
	return ShellMessage_UNKNOWN
}

func (m *ShellMessage) GetData() isShellMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ShellMessage) GetSize() *ShellSizeMessage {
	if x, ok := x.GetData().(*ShellMessage_Size); ok {
		return x.Size
	}
	return nil
}

func (x *ShellMessage) GetConnect() *ShellConnectMessage {
	if x, ok := x.GetData().(*ShellMessage_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *ShellMessage) GetError() string {
	if x, ok := x.GetData().(*ShellMessage_Error); ok {
		return x.Error
	}
	return ""
}

func (x *ShellMessage) GetPutdata() []byte {
	if x, ok := x.GetData().(*ShellMessage_Putdata); ok {
		return x.Putdata
	}
	return nil
}

type isShellMessage_Data interface {
	isShellMessage_Data()
}

type ShellMessage_Size struct {
	Size *ShellSizeMessage `protobuf:"bytes,3,opt,name=size,proto3,oneof"`
}

type ShellMessage_Connect struct {
	Connect *ShellConnectMessage `protobuf:"bytes,4,opt,name=connect,proto3,oneof"`
}

type ShellMessage_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ShellMessage_Putdata struct {
	Putdata []byte `protobuf:"bytes,6,opt,name=putdata,proto3,oneof"`
}

func (*ShellMessage_Size) isShellMessage_Data() {}

func (*ShellMessage_Connect) isShellMessage_Data() {}

func (*ShellMessage_Error) isShellMessage_Data() {}

func (*ShellMessage_Putdata) isShellMessage_Data() {}

type ShellSizeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"` // row
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"` // col
	X    uint32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`       // x
	Y    uint32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`       // y
}

func (x *ShellSizeMessage) Reset() {
	*x = ShellSizeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shell_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellSizeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellSizeMessage) ProtoMessage() {}

func (x *ShellSizeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellSizeMessage.ProtoReflect.Descriptor instead.
func (*ShellSizeMessage) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{1}
}

func (x *ShellSizeMessage) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellSizeMessage) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellSizeMessage) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ShellSizeMessage) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ShellConnectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // agent id
	Size *ShellSizeMessage `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ShellConnectMessage) Reset() {
	*x = ShellConnectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shell_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellConnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConnectMessage) ProtoMessage() {}

func (x *ShellConnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConnectMessage.ProtoReflect.Descriptor instead.
func (*ShellConnectMessage) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{2}
}

func (x *ShellConnectMessage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ShellConnectMessage) GetSize() *ShellSizeMessage {
	if x != nil {
		return x.Size
	}
	return nil
}

var File_shell_proto protoreflect.FileDescriptor

var file_shell_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0xcf, 0x02, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x69,
	0x7a, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x1a, 0x0a, 0x07, 0x70, 0x75, 0x74, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x07, 0x70, 0x75, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5f, 0x0a, 0x07, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x55, 0x54,
	0x50, 0x55, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x49, 0x5a, 0x45, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a,
	0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x06, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x10, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x69, 0x7a,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x22, 0x50, 0x0a, 0x13,
	0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x69, 0x7a,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shell_proto_rawDescOnce sync.Once
	file_shell_proto_rawDescData = file_shell_proto_rawDesc
)

func file_shell_proto_rawDescGZIP() []byte {
	file_shell_proto_rawDescOnce.Do(func() {
		file_shell_proto_rawDescData = protoimpl.X.CompressGZIP(file_shell_proto_rawDescData)
	})
	return file_shell_proto_rawDescData
}

var file_shell_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shell_proto_goTypes = []interface{}{
	(ShellMessage_MsgType)(0),   // 0: msg.ShellMessage.MsgType
	(*ShellMessage)(nil),        // 1: msg.ShellMessage
	(*ShellSizeMessage)(nil),    // 2: msg.ShellSizeMessage
	(*ShellConnectMessage)(nil), // 3: msg.ShellConnectMessage
}
var file_shell_proto_depIdxs = []int32{
	0, // 0: msg.ShellMessage.type:type_name -> msg.ShellMessage.MsgType
	2, // 1: msg.ShellMessage.size:type_name -> msg.ShellSizeMessage
	3, // 2: msg.ShellMessage.connect:type_name -> msg.ShellConnectMessage
	2, // 3: msg.ShellConnectMessage.size:type_name -> msg.ShellSizeMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shell_proto_init() }
func file_shell_proto_init() {
	if File_shell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shell_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shell_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellSizeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shell_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellConnectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_shell_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ShellMessage_Size)(nil),
		(*ShellMessage_Connect)(nil),
		(*ShellMessage_Error)(nil),
		(*ShellMessage_Putdata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shell_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shell_proto_goTypes,
		DependencyIndexes: file_shell_proto_depIdxs,
		EnumInfos:         file_shell_proto_enumTypes,
		MessageInfos:      file_shell_proto_msgTypes,
	}.Build()
	File_shell_proto = out.File
	file_shell_proto_rawDesc = nil
	file_shell_proto_goTypes = nil
	file_shell_proto_depIdxs = nil
}
