// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package handler

import (
	"sort"
	"sync"

	"github.com/google/uuid"
)

type PluginElement struct {
	Key   uuid.UUID
	Value *PluginLoad
}

type PluginSorterFunc func(a *PluginElement, b *PluginElement) bool

type PluginMap struct {
	Data sync.Map
}

func (m *PluginMap) Clear() {
	m.Data = sync.Map{}
}

func (m *PluginMap) Len() int {
	return len(m.Keys())
}

func (m *PluginMap) Get(k uuid.UUID) (*PluginLoad, bool) {
	ret, ok := m.Data.Load(k)
	if ret == nil {
		return nil, false
	}
	return ret.(*PluginLoad), ok
}

func (m *PluginMap) MustGet(k uuid.UUID) *PluginLoad {
	ret, ok := m.Get(k)
	if !ok {
		panic("key not found")
	}
	return ret
}

func (m *PluginMap) Set(k uuid.UUID, v *PluginLoad) {
	m.Data.Store(k, v)
}

func (m *PluginMap) SetIfAbsent(k uuid.UUID, v *PluginLoad) (*PluginLoad, bool) {
	ret, ok := m.Data.LoadOrStore(k, v)
	if ret == nil {
		panic("value is nil")
	}
	return ret.(*PluginLoad), ok
}

func (m *PluginMap) Delete(k uuid.UUID) {
	m.Data.Delete(k)
}

func (m *PluginMap) Has(k uuid.UUID) bool {
	_, ok := m.Data.Load(k)
	return ok
}

func (m *PluginMap) Range(f func(k uuid.UUID, v *PluginLoad) bool) {
	m.Data.Range(func(key, value interface{}) bool {
		return f(key.(uuid.UUID), value.(*PluginLoad))
	})
}

func (m *PluginMap) Keys() []uuid.UUID {
	var ret []uuid.UUID
	m.Range(func(key uuid.UUID, value *PluginLoad) bool {
		ret = append(ret, key)
		return true
	})
	return ret
}

func (m *PluginMap) Values() []*PluginLoad {
	var ret []*PluginLoad
	m.Range(func(key uuid.UUID, value *PluginLoad) bool {
		ret = append(ret, value)
		return true
	})
	return ret
}

func (m *PluginMap) Elements() []*PluginElement {
	var ret []*PluginElement
	m.Range(func(key uuid.UUID, value *PluginLoad) bool {
		ret = append(ret, &PluginElement{
			Key:   key,
			Value: value,
		})
		return true
	})
	return ret
}

func (m *PluginMap) Map() map[uuid.UUID]*PluginLoad {
	ret := make(map[uuid.UUID]*PluginLoad)
	m.Range(func(key uuid.UUID, value *PluginLoad) bool {
		ret[key] = value
		return true
	})
	return ret
}

func (m *PluginMap) SortElement(f PluginSorterFunc) []*PluginElement {
	ret := m.Elements()
	sort.SliceStable(ret, func(i, j int) bool {
		return f(ret[i], ret[j])
	})
	return ret
}

func (m *PluginMap) SortKey(f PluginSorterFunc) []uuid.UUID {
	res := m.SortElement(f)
	var ret []uuid.UUID
	for _, v := range res {
		ret = append(ret, v.Key)
	}
	return ret
}

func (m *PluginMap) SortValue(f PluginSorterFunc) []*PluginLoad {
	res := m.SortElement(f)
	var ret []*PluginLoad
	for _, v := range res {
		ret = append(ret, v.Value)
	}
	return ret
}
